name: NewsReader.CI

on: 
  push:
    paths: 
      - 'src/NewsReader/**'
      - '.github/workflows/**' 

jobs:
  Android:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - name: Install .NET MAUI
      run: |
        dotnet nuget locals all --clear
        dotnet workload install maui android
    - name: Build
      run: |
        cd src/NewsReader/NewsReader.Presentation
        dotnet publish -f:net7.0-android -c:Debug             # Workaround for https://github.com/dotnet/linker/issues/3126

  Windows:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - name: Install .NET MAUI
      run: |
        dotnet nuget locals all --clear
        dotnet workload install maui
    - name: Build
      run: |
        cd src/NewsReader/NewsReader.Presentation
        dotnet publish -f:net7.0-windows10.0.19041.0 -c:Release

  iOS:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Set Xcode version
        run: |
          sudo xcode-select -s "/Applications/Xcode_14.2.app"
      - name: Install .NET MAUI
        run: |
          dotnet nuget locals all --clear 
          dotnet workload install maui ios
      - name: Build
        run: |
          cd src/NewsReader/NewsReader.Presentation
          dotnet build -f net7.0-ios -c Debug /p:packageApp=false /p:buildForSimulator=true /p:ArchiveOnBuild=false
        
  Test:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
    - name: Domain.Test
      run: |
        cd src/NewsReader/NewsReader.Domain.Test
        dotnet test -c:Release
