name: System.Waf.CI

on: 
  push:
    paths: 
      - 'src/System.Waf/**'
      - '.github/workflows/**' 

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Clean
      run: dotnet clean -c Release && dotnet nuget locals all --clear
    
    - name: Build
      run: dotnet build ./src/System.Waf/System.Waf.sln -c Release
    
    - name: Test
      run: dotnet test ./src/System.Waf/System.Waf.sln -c Release --no-build
